import type { Metadata } from "next";
import {  Poppins } from "next/font/google";
import "./globals.css";

import Navbar from "./components/navbar";
import NavbarContainer from "./components/NavbarContainer";
import Providers from "./Providers";
import { Toaster } from "sonner";
import Footer from "./components/Footer";

const poppins = Poppins({
  subsets: ["latin"],
  variable: "--font-poppins",
  weight: [ "500" ], // choose weights
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${poppins.variable} bg-slate-100 antialiased`}>
        <Providers>
          <NavbarContainer>
            <Navbar />
          </NavbarContainer>
        

          {children}
          <Footer/>
          <Toaster />
        </Providers>
      </body>
    </html>
  );
}
